-- CyberSafe Learn Security modules
-- Paste and run this entire file in Supabase SQL Editor.
-- It contains no temporary tables and is safe to run again.

alter table public.modules add column if not exists category text;

insert into public.modules (
  slug, title, description, content, difficulty, category, order_index, estimated_minutes
) values
('password-security', 'Password Security Basics', 'Learn how to create, manage, and protect strong passwords.', E'WHY THIS MATTERS\nReused or predictable passwords can expose several accounts after one data breach.\n\nSCENARIO\nA giveaway site asks you to reuse your school email password.\n\nWARNING SIGNS\n• A site asks you to reuse an important password.\n• Your password is short or based on personal information.\n• Two-factor authentication is not enabled.\n\nPRACTICAL ACTIONS\n1. Use a unique, long password or passphrase for each important account.\n2. Turn on two-factor authentication.\n3. Use a trusted password manager.\n\nKEY TAKEAWAY\nUse a different strong password for every important account.', 'Beginner', 'Social engineering', 1, 10),
('phishing-awareness', 'Phishing Awareness', 'Learn how to identify common phishing attempts and avoid falling for them.', E'WHY THIS MATTERS\nPhishing messages imitate trusted organisations to steal login or payment information.\n\nSCENARIO\nAn email says your parcel is waiting and asks for a small payment through a shortened link.\n\nWARNING SIGNS\n• An unexpected payment or account warning.\n• A shortened or misspelled web address.\n• Threats that your account will be lost soon.\n\nPRACTICAL ACTIONS\n1. Check the sender address and web address independently.\n2. Do not enter details after following an unexpected link.\n3. Visit the company website or app yourself.\n\nKEY TAKEAWAY\nVerify through the real company website, not a message link.', 'Beginner', 'Social engineering', 2, 10),
('whatsapp-account-safety', 'Protect Your WhatsApp Account', 'Keep your WhatsApp account secure from verification-code and takeover scams.', E'WHY THIS MATTERS\nA WhatsApp verification code can let a scammer register your number on another device.\n\nSCENARIO\nA contact says they accidentally sent their WhatsApp code to you and asks you to forward it.\n\nWARNING SIGNS\n• A request for a six-digit code.\n• A friend acting unusually urgent.\n• A verification message you did not request.\n\nPRACTICAL ACTIONS\n1. Never share a verification code.\n2. Enable WhatsApp two-step verification.\n3. Contact the person another way if their account may be compromised.\n\nKEY TAKEAWAY\nVerification codes are private—never forward them.', 'Beginner', 'Social engineering', 3, 15),
('banking-safety-essentials', 'Banking Safety Essentials', 'Protect your banking details and respond safely to suspicious alerts.', E'WHY THIS MATTERS\nCriminals copy bank branding and create urgency so that you act before checking a message.\n\nSCENARIO\nYou receive an SMS saying your banking profile will be blocked unless you approve a request immediately.\n\nWARNING SIGNS\n• Pressure to act immediately.\n• A link outside your bank''s official app or website.\n• A request for a PIN, password, or OTP.\n\nPRACTICAL ACTIONS\n1. Open your official banking app directly.\n2. Call the number on the back of your bank card if unsure.\n3. Never share a PIN, password, card number, or OTP.\n\nKEY TAKEAWAY\nUse your official banking app or a verified bank number, not the message link.', 'Beginner', 'Banking', 4, 30),
('sim-swap-response', 'Stop a SIM-Swap Attack', 'Know the early warning signs and urgent steps that protect your accounts.', E'WHY THIS MATTERS\nIn a SIM-swap attack, criminals move your phone number to their SIM card and intercept SMS verification codes.\n\nSCENARIO\nYour phone suddenly loses signal and you receive a SIM-swap notification.\n\nWARNING SIGNS\n• Unexpected loss of mobile signal.\n• A SIM-swap request you did not make.\n• Password-reset messages or bank alerts you did not trigger.\n\nPRACTICAL ACTIONS\n1. Call your mobile network from another phone immediately.\n2. Contact your bank and secure accounts using SMS verification.\n3. Change important passwords from a safe device.\n\nKEY TAKEAWAY\nTreat unexplained loss of signal as urgent.', 'Intermediate', 'Banking', 5, 20),
('safe-online-shopping', 'Shop and Sell Safely Online', 'Recognise payment, delivery, and marketplace scams before you lose money.', E'WHY THIS MATTERS\nMarketplace scams use fake payment screenshots, fake couriers, or promises that money will reflect later.\n\nSCENARIO\nA buyer sends a payment screenshot and asks a courier to collect your item before funds reflect.\n\nWARNING SIGNS\n• Pressure to release an item quickly.\n• A screenshot instead of cleared funds.\n• A buyer arranging an unfamiliar courier.\n\nPRACTICAL ACTIONS\n1. Release goods only after cleared funds appear in your banking app.\n2. Do not trust payment screenshots alone.\n3. Keep payments on the marketplace where possible.\n\nKEY TAKEAWAY\nA screenshot is not payment.', 'Beginner', 'Banking', 6, 20),
('digital-safety-schools', 'Digital Safety for Schools', 'Build safer habits for shared devices, learning platforms, and class groups.', E'WHY THIS MATTERS\nShared devices, open browser sessions, and public class chats can expose a learner''s account or personal information.\n\nSCENARIO\nA learner logs in to a shared school computer and sees a prompt asking to save their password.\n\nWARNING SIGNS\n• A browser offering to save a password on a shared computer.\n• An account still logged in after a lesson.\n• Unknown links in a class group.\n\nPRACTICAL ACTIONS\n1. Sign out fully and do not save passwords.\n2. Use trusted school platforms only.\n3. Keep personal details out of public class chats.\n\nKEY TAKEAWAY\nOn a shared device, sign out completely.', 'Beginner', 'School resources', 7, 25),
('safe-online-research', 'Safe Online Research', 'Check sources, avoid misinformation, and use online information responsibly.', E'WHY THIS MATTERS\nFalse information spreads quickly when it creates fear, anger, or urgency.\n\nSCENARIO\nA class group shares a shocking cybercrime post and asks everyone to repost it immediately.\n\nWARNING SIGNS\n• A demand to share before it is deleted.\n• No named or reliable source.\n• Old information presented as a new emergency.\n\nPRACTICAL ACTIONS\n1. Check the source, author, and publication date.\n2. Use official organisations to confirm important claims.\n3. Pause before reposting fear-based content.\n\nKEY TAKEAWAY\nCheck the source, date, and evidence before sharing.', 'Beginner', 'School resources', 8, 20),
('public-wifi-safety', 'Stay Safe on Public Wi-Fi', 'Use public networks more safely and avoid risky prompts and logins.', E'WHY THIS MATTERS\nPublic Wi-Fi can be run by anyone, including criminals using fake network names or malicious sign-in pages.\n\nSCENARIO\nYou connect to free Wi-Fi and a pop-up asks you to install a security certificate.\n\nWARNING SIGNS\n• A network name that almost matches the venue.\n• A request to install a profile, certificate, or app.\n• A public connection asking for banking credentials.\n\nPRACTICAL ACTIONS\n1. Avoid banking and sensitive logins on public Wi-Fi.\n2. Do not install unknown profiles or certificates.\n3. Use mobile data for important tasks.\n\nKEY TAKEAWAY\nUse public Wi-Fi only for low-risk browsing.', 'Beginner', 'School resources', 9, 15),
('cyberbullying-support', 'Respond to Cyberbullying Safely', 'Support yourself or others without spreading harmful content further.', E'WHY THIS MATTERS\nCyberbullying can grow when others comment, repost, or share screenshots publicly.\n\nSCENARIO\nSomeone posts hurtful messages about a learner and asks others to share screenshots.\n\nWARNING SIGNS\n• Repeated hurtful messages or threats.\n• Pressure to share embarrassing content.\n• A post encouraging others to target someone.\n\nPRACTICAL ACTIONS\n1. Save evidence privately without amplifying harm.\n2. Block and report the account.\n3. Tell a trusted adult, educator, or support person.\n\nKEY TAKEAWAY\nSave evidence, report it, and get support—do not amplify it.', 'Beginner', 'School resources', 10, 25),
('personal-information', 'Protect Your Personal Information', 'Know what information to keep private and how identity scams begin.', E'WHY THIS MATTERS\nIdentity scammers collect details such as an ID number, address, date of birth, and OTP to impersonate people.\n\nSCENARIO\nA caller claiming to be from a service provider asks for your ID number and OTP to confirm an upgrade.\n\nWARNING SIGNS\n• An unexpected request for an ID number or OTP.\n• A caller asking you to keep the request secret.\n• A link requesting a photo of an identity document.\n\nPRACTICAL ACTIONS\n1. Do not provide OTPs or identity details on unexpected calls.\n2. Verify requests using an official number or website.\n3. Avoid posting sensitive documents online.\n\nKEY TAKEAWAY\nKeep identity details and OTPs private.', 'Beginner', 'Social engineering', 11, 20),
('safe-job-search', 'Find Jobs Safely Online', 'Avoid fake job offers, recruitment fees, and identity-harvesting scams.', E'WHY THIS MATTERS\nFake job adverts promise easy work, then request a payment or personal documents before a real interview.\n\nSCENARIO\nA recruiter offers you a job but asks for a training fee and a copy of your ID before an interview.\n\nWARNING SIGNS\n• A job offer without a real interview.\n• A request for a fee, voucher, or payment.\n• An email address that does not match the employer''s official website.\n\nPRACTICAL ACTIONS\n1. Never pay an upfront fee to secure a job.\n2. Verify vacancies on the employer''s official website.\n3. Share only information needed for a genuine application.\n\nKEY TAKEAWAY\nA genuine employer will not charge you to secure a job.', 'Beginner', 'Social engineering', 12, 20)
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  content = excluded.content,
  difficulty = excluded.difficulty,
  category = excluded.category,
  order_index = excluded.order_index,
  estimated_minutes = excluded.estimated_minutes;

-- Check which modules already have a quiz connected.
select
  module.id as module_id,
  module.slug,
  module.title as module_title,
  module.category,
  module.order_index,
  quiz.id as quiz_id,
  quiz."Title" as quiz_title
from public.modules as module
left join public."Quizz" as quiz on quiz.module_id = module.id
order by module.order_index, module.title;
